speedups:
  # this complicates sort direction in Gem::Version sorts
  sort_vs_sort_by: false
  each_with_index_vs_while: false
  rescue_vs_respond_to: true
  module_eval: true
  shuffle_first_vs_sample: true
  for_loop_vs_each: true
  map_flatten_vs_flat_map: true
  reverse_each_vs_reverse_each: true
  select_first_vs_detect: true
  fetch_with_argument_vs_block: true
  keys_each_vs_each_key: true
  hash_merge_bang_vs_hash_brackets: true
  block_vs_symbol_to_proc: true
  proc_call_vs_yield: true
  gsub_vs_tr: true
  select_last_vs_reverse_detect: true
  getter_vs_attr_reader: true
  setter_vs_attr_writer: true
exclude_paths:
  - api/vendor/**/*.rb
  - db/schema.rb
  - storage/**/*.rb
  - vendor/**/*.rb
