inherit_from: .rubocop_todo.yml

inherit_mode:
  merge:
    - Exclude

require:
  - rubocop-rspec
  - rubocop-performance

AllCops:
  NewCops: enable
  Exclude:
    - tmp/**/*
  TargetRubyVersion: 2.7
  SuggestExtensions: false

Layout/BeginEndAlignment:
  Enabled: true

Layout/EmptyLinesAroundAttributeAccessor:
  Enabled: true

Layout/FirstHashElementIndentation:
  Enabled: true
  EnforcedStyle: consistent

Layout/LineLength:
  Enabled: true
  Max: 120
  AllowedPatterns:
    - ^.*_REGEXP\s=.*

Layout/MultilineMethodCallIndentation:
  Enabled: true
  EnforcedStyle: indented

Layout/SpaceAroundMethodCallOperator:
  Enabled: true

Layout/SpaceBeforeBrackets:
  Enabled: true

Metrics/BlockLength:
  AllowedMethods:
    - describe
    - context
    - included
  Exclude:
    - spec/**/*

Metrics/MethodLength:
  Enabled: true
  Max: 15
  Exclude:
    - spec/**/*

Lint/AmbiguousAssignment:
  Enabled: true

Lint/AmbiguousBlockAssociation:
  Exclude:
    - spec/**/*

Lint/BinaryOperatorWithIdenticalOperands:
  Enabled: true

Lint/ConstantDefinitionInBlock:
  Enabled: true

Lint/DeprecatedConstants:
  Enabled: true

Lint/DeprecatedOpenSSLConstant:
  Enabled: true

Lint/DuplicateBranch:
  Enabled: true

Lint/DuplicateElsifCondition:
  Enabled: true

Lint/DuplicateRegexpCharacterClassElement:
  Enabled: true

Lint/DuplicateRequire:
  Enabled: true

Lint/DuplicateRescueException:
  Enabled: true

Lint/EmptyBlock:
  Enabled: true

Lint/EmptyClass:
  Enabled: true

Lint/EmptyConditionalBody:
  Enabled: true

Lint/EmptyFile:
  Enabled: true

Lint/FloatComparison:
  Enabled: true

Lint/IdentityComparison:
  Enabled: true

Lint/LambdaWithoutLiteralBlock:
  Enabled: true

Lint/MissingSuper:
  Enabled: true

Lint/MixedRegexpCaptureTypes:
  Enabled: true

Lint/NoReturnInBeginEndBlocks:
  Enabled: true

Lint/NumberedParameterAssignment:
  Enabled: true

Lint/OrAssignmentToConstant:
  Enabled: true

Lint/OutOfRangeRegexpRef:
  Enabled: true

Lint/RaiseException:
  Enabled: true

Lint/RedundantDirGlobSort:
  Enabled: true

Lint/SelfAssignment:
  Enabled: true

Lint/StructNewOverride:
  Enabled: false

Lint/SymbolConversion:
  Enabled: true

Lint/ToEnumArguments:
  Enabled: true

Lint/TopLevelReturnWithArgument:
  Enabled: true

Lint/TrailingCommaInAttributeDeclaration:
  Enabled: true

Lint/TripleQuotes:
  Enabled: true

Lint/UnexpectedBlockArity:
  Enabled: true

Lint/UnmodifiedReduceAccumulator:
  Enabled: true

Lint/UnreachableLoop:
  Enabled: true

Lint/UselessMethodDefinition:
  Enabled: true

Lint/UselessTimes:
  Enabled: true

Performance/AncestorsInclude:
  Enabled: true

Performance/BigDecimalWithNumericArgument:
  Enabled: true

Performance/BlockGivenWithExplicitBlock:
  Enabled: true

Performance/CaseWhenSplat:
  Enabled: true

Performance/ChainArrayAllocation:
  Enabled: false

Performance/CollectionLiteralInLoop:
  Enabled: true

Performance/ConstantRegexp:
  Enabled: true

Performance/IoReadlines:
  Enabled: true

Performance/MethodObjectAsBlock:
  Enabled: true

Performance/OpenStruct:
  Enabled: true

Performance/RedundantEqualityComparisonBlock:
  Enabled: true

Performance/RedundantSortBlock:
  Enabled: true

Performance/RedundantSplitRegexpArgument:
  Enabled: true

Performance/RedundantStringChars:
  Enabled: true

Performance/ReverseFirst:
  Enabled: true

Performance/SortReverse:
  Enabled: true

Performance/Squeeze:
  Enabled: true

Performance/StringInclude:
  Enabled: true

Performance/Sum:
  Enabled: true

RSpec/ContextWording:
  Enabled: true
  Exclude:
    - spec/support/shared_contexts/*.rb
    - spec/support/shared_contexts/**/*.rb
    - spec/support/shared_examples/*.rb
    - spec/support/shared_examples/**/*.rb

RSpec/DescribeClass:
  Enabled: true

RSpec/DescribedClassModuleWrapping:
  Enabled: true

RSpec/EmptyExampleGroup:
  Enabled: true

RSpec/ExampleLength:
  Max: 15
  Enabled: true
  CountAsOne:
    - array
    - hash

RSpec/ImplicitSubject:
  Enabled: true

RSpec/LetSetup:
  Enabled: false

RSpec/MessageExpectation:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: true
  Max: 10

RSpec/MultipleMemoizedHelpers:
  Enabled: true
  Max: 10
  Exclude:
    - spec/support/shared_contexts/*.rb

RSpec/MultipleSubjects:
  Enabled: true

RSpec/NestedGroups:
  Max: 10

RSpec/Pending:
  Enabled: true

RSpec/ScatteredSetup:
  Enabled: true

RSpec/SharedContext:
  Enabled: true

RSpec/VariableName:
  Enabled: true
  EnforcedStyle: snake_case
  AllowedPatterns:
    - ^Accept-Language
    - ^Authorization
    - ^Cookie
    - ^Fingerprint
    - ^If-Match
    - ^User-Agent

Style/AccessorGrouping:
  Enabled: true

Style/ArgumentsForwarding:
  Enabled: true

Style/ArrayCoercion:
  Enabled: true

Style/AsciiComments:
  Enabled: true
  AllowedChars:
    - €

Style/BisectedAttrAccessor:
  Enabled: true

Style/CaseLikeIf:
  Enabled: true

Style/CollectionCompact:
  Enabled: true

Style/CombinableLoops:
  Enabled: true

Style/Documentation:
  Enabled: false

Style/DocumentDynamicEvalDefinition:
  Enabled: true

Style/EndlessMethod:
  Enabled: true

Style/ExplicitBlockArgument:
  Enabled: true

Style/ExponentialNotation:
  Enabled: true

Style/FetchEnvVar:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: true
  SafeAutoCorrect: true

Style/GlobalStdStream:
  Enabled: true

Style/HashAsLastArrayItem:
  Enabled: true

Style/HashEachMethods:
  Enabled: true

Style/HashConversion:
  Enabled: true

Style/HashExcept:
  Enabled: true

Style/HashLikeCase:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Style/IfWithBooleanLiteralBranches:
  Enabled: true

Style/KeywordParametersOrder:
  Enabled: true

Style/NegatedIfElseCondition:
  Enabled: true

Style/NilLambda:
  Enabled: true

Style/OptionalBooleanParameter:
  Enabled: true

Style/RedundantArgument:
  Enabled: true

Style/RedundantAssignment:
  Enabled: true

Style/RedundantFetchBlock:
  Enabled: false

Style/RedundantFileExtensionInRequire:
  Enabled: true

Style/RedundantRegexpCharacterClass:
  Enabled: true

Style/RedundantRegexpEscape:
  Enabled: true

Style/RedundantSelfAssignment:
  Enabled: true

Style/SingleArgumentDig:
  Enabled: true

Style/SlicingWithRange:
  Enabled: true

Style/SoleNestedConditional:
  Enabled: true

Style/StringChars:
  Enabled: true

Style/StringConcatenation:
  Enabled: true

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/SwapValues:
  Enabled: true

Style/TrailingCommaInArguments:
  Enabled: true
  EnforcedStyleForMultiline: consistent_comma

Style/TrailingCommaInArrayLiteral:
  Enabled: true
  EnforcedStyleForMultiline: consistent_comma

Style/TrailingCommaInHashLiteral:
  Enabled: true
  EnforcedStyleForMultiline: consistent_comma
